---

- name: install chrony
  yum:
    name: chrony
    state: present

- name: configure chrony
  template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
  notify:
    - restart chronyd

- name: start chronyd
  systemd:
    name: chronyd
    state: started

- name: enable chronyd
  systemd:
    name: chronyd
    enabled: yes