---

- name: download redis_exporter zipped archive
  get_url:
    url: https://jfrog.example.com/artifactory/generic-local/redis_exporter-v1.3.5.linux-amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/redis_exporter-v1.3.5.linux-amd64.tar.gz"

- name: extract redis_exporter zipped archive
  unarchive:
    src: "{{ ansible_env.HOME }}/redis_exporter-v1.3.5.linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes

- name: copy redis_exporter bin file
  copy:
    src: "{{ ansible_env.HOME }}/redis_exporter-v1.3.5.linux-amd64/redis_exporter"
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve

- name: create redis_exporter service file
  template:
    src: templates/redis_exporter.service.j2
    dest: /etc/systemd/system/redis_exporter.service
  notify:
    - daemon reload
    - restart redis_exporter

- name: start/enable redis_exporter
  systemd:
    name: redis_exporter
    state: started
    enabled: yes
