---

- name: install nginx
  yum:
    name: nginx
    state: present

- name: install nginx dynamic modules
  yum:
    name: "{{ nginx_modules }}"
    state: present
  when: (nginx_modules is defined) and (nginx_modules|length > 0)