galaxy_info:
  author: Irakli Korpashvili
  description: Provisions Wiki.js on CentOS 7 with Nginx reverse proxy.
  company: example

  min_ansible_version: 2.4

  platforms:
  - name: CentOS
    versions:
    - 7
