---

- name: create dir for rabbitmq-server.service override
  file:
    path: /etc/systemd/system/rabbitmq-server.service.d/
    state: directory
    owner: root
    group: root

- name: override default service parameters
  copy:
    src: files/override.conf
    dest: /etc/systemd/system/rabbitmq-server.service.d/override.conf
  notify:
    - restart rabbitmq-server

- name: enable rabbitmq management ui
  shell: >
    rabbitmq-plugins enable rabbitmq_management
  args:
    creates: "/etc/rabbitmq/enabled_plugins"
  notify:
    - restart rabbitmq-server

- name: configure erlang cookie
  copy:
    content: HUAAZQBQBVKBEJNPGUVV
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  notify:
    - restart rabbitmq-server

- name: configure rabbitmq.conf
  template:
    src: "templates/rabbitmq.conf.j2"
    dest: "/etc/rabbitmq/rabbitmq.conf"
    owner: "root"
    group: "rabbitmq"
    mode: 0640
  notify:
    - restart rabbitmq-server

- name: configure rabbitmq-env.conf
  template:
    src: "templates/rabbitmq-env.conf.j2"
    dest: "/etc/rabbitmq/rabbitmq-env.conf"
    owner: "root"
    group: "rabbitmq"
    mode: 0640
  notify:
    - restart rabbitmq-server