---

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes