---
- name: add alertmanager user
  user:
    name: alertmanager
    create_home: no
    shell: /bin/false

- name: download alertmanager zipped archive
  get_url:
    url: https://jfrog.example.com/artifactory/generic-local/alertmanager-0.20.0.linux-amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/alertmanager-0.20.0.linux-amd64.tar.gz"

- name: extract alertmanager zipped archive
  unarchive:
    src: "{{ ansible_env.HOME }}/alertmanager-0.20.0.linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes

- name: create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  with_items:
    - /etc/alertmanager
    - /var/lib/alertmanager

- name: copy alertmanager bin files
  copy:
    src: "{{ ansible_env.HOME }}/alertmanager-0.20.0.linux-amd64/{{ item }}"
    dest: /usr/local/bin/
    owner: alertmanager
    group: alertmanager
    remote_src: yes
    mode: preserve
  with_items:
    - alertmanager
    - amtool
  notify:
    - restart alertmanager

- name: configure alertmanager
  template:
    src: templates/alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
  notify:
    - restart alertmanager

- name: generate alertmanager service file
  copy:
    src: files/alertmanager.service
    dest: /etc/systemd/system/alertmanager.service
  notify:
    - daemon reload
    - restart alertmanager

- name: start/enable alertmanager
  systemd:
    name: alertmanager
    state: started
    enabled: yes
