---

- name: install apache
  yum:
   name: httpd
   state: present

- name: install mod_ssl
  yum:
    name: mod_ssl
    state: present

- name: install mariadb
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ phpipam_mariadb_packages }}"

- name: start/enable mariadb
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: install php packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ phpipam_php_packages }}"
  notify: restart php-fpm