---

- name: install glusterfs server
  yum:
    name: glusterfs-server
    state: present

- name: start/enable glusterd
  systemd:
    name: glusterd
    state: started
    enabled: yes

- name: create a trusted storage pool
  shell: gluster peer probe "{{ item['hostname'] }}"
  with_items:
    - "{{ glusterfs_peer_nodes }}"
  run_once: true
