---

- name: install nginx
  yum:
    name: nginx
    state: present

- name: create directory for ssl files
  file:
    path: "{{ jenkins_nginx_ssl_dir }}"
    state: directory

- name: copy ssl files
  copy:
    src: "{{ item }}"
    dest: "{{ jenkins_nginx_ssl_dir }}"
  with_fileglob:
    - files/ssl/*
  notify:
    - restart nginx

- name: delete nginx default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: configure nginx
  template:
    src: "templates/nginx/jenkins.conf.j2"
    dest: "/etc/nginx/conf.d/jenkins.conf"
  notify:
    - restart nginx

- name: start nginx
  systemd:
    name: nginx
    state: started

- name: enable nginx
  systemd:
    name: nginx
    enabled: true
