---

postgresql12_version: "12"
postgresql12_base_dir: "/var/lib/pgsql"
postgresql12_data_dir: "{{ postgresql12_base_dir }}/{{ postgresql12_version }}/data"
postgresql12_bin_dir: "/usr/pgsql-{{ postgresql12_version }}/bin"

# apply on both (master, slave)
postgresql12_mode: master
postgresql12_master_host: "{{ inventory_hostname }}"
postgresql12_password: "example"

### Undefined variables
# postgresql_shared_preload_libraries 

# configuration
postgresql12_listen_address: "*"
postgresql12_port: "5432"
postgresql12_max_connections: "400"
postgresql12_shared_buffers: "2048MB"
postgresql12_work_mem: "12MB"
postgresql12_maintenance_work_mem: "320MB"
postgresql12_effecitve_cache_size: "6GB"
postgresql12_effective_io_concurrency: "300"
postgresql12_max_parallel_workers: "16"
postgresql12_max_parallel_workers_per_gather: "8"
postgresql12_max_parallel_maintenance_workers: "8"
postgresql12_max_worker_processes: "16"
postgresql12_checkpoint_completion_target: "0.9"
postgresql12_checkpoint_timeout: "15min"
postgresql12_synchronous_commit: "local"
postgresql12_default_statistics_target: "100"
postgresql12_random_page_cost: "2"
postgresql12_huge_pages: "try"
postgresql12_wal_level: "replica"
postgresql12_max_wal_size: "2GB"
postgresql12_min_wal_size: "1GB"
postgresql12_max_wal_senders: "10"
postgresql12_wal_keep_segments: "100"
postgresql12_wal_sender_timeout: "60s"
postgresql12_hot_standby: "on"
postgresql12_max_standby_archive_delay: "900s"
postgresql12_max_standby_streaming_delay: "900s"
postgresql12_seq_page_cost: "0.7"
postgresql12_wal_receiver_status_interval: "10s"
postgresql12_hot_standby_feedback: "on"
postgresql12_wal_receiver_timeout: "60s"
postgresql12_wal_retrieve_retry_interval: "5s"
postgresql12_wal_compression: "off"
postgresql12_wal_buffers: "1MB"
postgresql12_bgwriter_delay: "100ms"
postgresql12_log_directory: "/var/log/postgresql"
postgresql12_log_filename: "postgresql.log"
postgresql12_log_truncate_on_rotation: "on"
postgresql12_log_rotation_age: "3d"
postgresql12_log_rotation_size: "512MB"
postgresql12_log_min_messages: "warning"
postgresql12_log_min_error_statement: "error"
postgresql12_log_checkpoints: "off"
postgresql12_log_connections: "off"
postgresql12_log_disconnections: "off"
postgresql12_log_duration: "off"
postgresql12_log_line_prefix: "%t <%d %u %r> %%"
postgresql12_log_lock_waits: "on"
postgresql12_log_statement: "mod"
postgresql12_log_replication_commands: "off"
postgresql12_log_timezone: "Asia/Tbilisi"
postgresql12_log_min_duration_statement: "10s"
