---

- name: restart postgresql
  systemd:
    name: postgresql-12
    state: restarted
    daemon_reload: yes

- name: daemon reload
  systemd:
    daemon_reload: yes

- name: restart postgres_exporter
  systemd:
    name: postgres_exporter
    state: restarted
    daemon_reload: yes