---

- name: download blackbox_exporter zipped archive
  get_url:
    url: https://jfrog.example.com/artifactory/generic-local/blackbox_exporter-0.16.0.linux-amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/blackbox_exporter-0.16.0.linux-amd64.tar.gz"

- name: extract blackbox_exporter zipped archive
  unarchive:
    src: "{{ ansible_env.HOME }}/blackbox_exporter-0.16.0.linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes

- name: create a blackbox_exporter directory
  file:
    path: /etc/blackbox
    state: directory

- name: copy blackbox_exporter bin file
  copy:
    src: "{{ ansible_env.HOME }}/blackbox_exporter-0.16.0.linux-amd64/blackbox_exporter"
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve

- name: copy blackbox_exporter config files
  copy:
    src: files/blackbox.yml
    dest: /etc/blackbox/
  notify:
    - restart blackbox_exporter

- name: generate blackbox_exporter service file
  template:
    src: templates/blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
  notify:
    - daemon reload
    - restart blackbox_exporter

- name: start/enable blackbox_exporter
  systemd:
    name: blackbox_exporter
    state: started
    enabled: yes
