---

prometheus_jobs: []
  # - name: prometheus
  #   scrape_interval: 15s
  #   port: 9090
  #   targets:
  #     - "{{ inventory_hostname }}"
  # - name: node_exporter
  #   scrape_interval: 15s
  #   port: 9100
  #   targets: "{{ groups['all'] }}"

prometheus_retention_time: 30d
prometheus_external_url: https://prometheus.example.com

prometheus_scrape_interval: 1m
prometheus_scrape_timeout: 30s


blackbox_url: blackbox.example.com
blackbox_http_targets: []
blackbox_tcp_targets: []
blackbox_icmp_targets: []
