galaxy_info:
  author: Irakli Korpashvili
  description: Provisions PostgreSQL 12 master/slave streaming replication cluster with hot standby.
  company: example

  license: BSD

  min_ansible_version: 2.4

  platforms:
  - name: CentOS
    versions:
    - 7