---
- name: add nginx repo
  yum_repository:
    name: nginx
    description: Nginx Repository
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes

- name: install nginx
  yum:
    name: nginx
    state: present

- name: create directory for ssl files
  file:
    path: "{{ artifactory_nginx_ssl_dir }}"
    state: directory

- name: copy ssl files
  copy:
    src: "{{ item }}"
    dest: "{{ artifactory_nginx_ssl_dir }}"
  with_fileglob:
    - files/ssl/*
  notify:
    - restart nginx

- name: delete nginx default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: configure nginx
  copy:
    src: files/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: configure nginx vhost
  copy:
    src: "files/nginx/artifactory.conf"
    dest: "/etc/nginx/conf.d/artifactory.conf"
  notify:
    - restart nginx

- name: start nginx
  systemd:
    name: nginx
    state: started

- name: enable nginx
  systemd:
    name: nginx
    enabled: true
